INSERT INTO TEAM(TEAM_ID, NAME, LEAGUE) VALUES(1, 'Barcelona', 'La Liga');
INSERT INTO TEAM(TEAM_ID, NAME, LEAGUE) VALUES(2, 'Galatasaray', 'Super Lig');
INSERT INTO TEAM(TEAM_ID, NAME, LEAGUE) VALUES(3, 'Real Madrid', 'La Liga');
INSERT INTO TEAM(TEAM_ID, NAME, LEAGUE) VALUES(4, 'Bayern', 'Bundesliga');
INSERT INTO TEAM(TEAM_ID, NAME, LEAGUE) VALUES(5, 'PSG', 'Ligue 1');

INSERT INTO PLAYER VALUES(1, 'Frenkie', 'De Jong');
INSERT INTO PLAYER VALUES(2, 'Ferran', 'Torres');
INSERT INTO PLAYER VALUES(3, 'Olimpiu', 'Morutan');
INSERT INTO PLAYER VALUES(4, 'Kaan', 'Arslan');
INSERT INTO PLAYER VALUES(5, 'Karim', 'Benzema');
INSERT INTO PLAYER VALUES(6, 'Eden', 'Hazard');
INSERT INTO PLAYER VALUES(7, 'Robert', 'Lewandowski');
INSERT INTO PLAYER VALUES(8, 'Kylian', 'Mbappe');
INSERT INTO PLAYER VALUES(9, 'Lionel', 'Messi');

INSERT INTO PLAYER_TEAM VALUES (1, 1);
INSERT INTO PLAYER_TEAM VALUES (1, 2);
INSERT INTO PLAYER_TEAM VALUES (2, 3);
INSERT INTO PLAYER_TEAM VALUES (2, 4);
INSERT INTO PLAYER_TEAM VALUES (3, 5);
INSERT INTO PLAYER_TEAM VALUES (3, 6);
INSERT INTO PLAYER_TEAM VALUES (4, 7);
INSERT INTO PLAYER_TEAM VALUES (5, 8);
INSERT INTO PLAYER_TEAM VALUES (5, 9);
